export { default as NavBar } from "./NavBar"
export { default as AboutMe } from "./AboutMe"
export { default as Portfolio } from "./Portfolio"
export { default as TechStack } from "./TechStack"
export { default as Resume } from "./Resume"
export { default as Contact } from "./Contact"